### ISSUE TITLE
Migrate from CoffeeScrip to vanilla JavaScript

### ISSUE THREAD

**Issue by jpillora** [jpillora/node-glob-all#10]
CoffeeScript is dead, this package needs to be migrated to vanilla JS

**Comment by jpillora** [comment]
@PAEz feel free to send a PR 😉

**Comment by puranjayjain** [comment]
@jpillora try http://js2.coffee/ it will really speed up your process. or shall I send a PR ? :grin:

**Comment by jpillora** [comment]
js2coffee is step 1, the source will still need to be cleaned up, comments readded, use node standard library inherit instead of coffeescript extend, so yep, a PR would be good :)

**Comment by jpillora** [comment]
Closed by https://github.com/jpillora/node-glob-all/commit/30e092bfe3a0c76c92e1aeab6fca7df5316992a7 thanks @puranjayjain
