### ISSUE TITLE
Glob pattern not acting as expected

### ISSUE THREAD

**Issue by jrbenito** [jpillora/node-glob-all#14]
Hi there,

From `node-glob` [documentation](https://github.com/isaacs/node-glob/blob/master/README.md):

> `!(pattern|pattern|pattern)``  Matches anything that does not match any of the patterns provided.

 I understand that `'**/*.!(css|js)'` shall list everything except `*.css` and `*.js`.

However on my tests it does not:

```
$ glob-all '**/*.!(css|js)' | sort >wglob
$ find ./ -type f | egrep --color=no -v "\.(css|js)" | sort | sed -e 's#^\./##' >wfind
```

`sed` was used to remove `./` from the start of the lines in `wfind` since find returns the path in relation to local directory (`./`). Then, a simple diff of results:

```
$ diff wfind wglob
20a21,24
> assets/css/jquery.fancybox.css
> assets/css/jquery.fancybox-thumbs.css
> assets/css/style-27vrduj1jopliavvnzi7ibndpmbvg7lzo4a2uswrsi4m5vwauf2qi8s1v3or.min.css
> assets/css/style-nuvue6sithwirecbhvw3dkaobiojqvtadsnhguwi7k04xklybw5djl1smadp.min.css
35a40,43
> assets/js/jquery.fancybox.js
> assets/js/jquery.fancybox-thumbs.js
> assets/js/script-i4qo6jx6jji9fg0dftpya6ivemizsbow4fhow76d8dwpm7m1wbvi378ssumx.min.js
> assets/js/scrip-tu4ziscb5jrkjxubeugdgizktyuugflfq5jvgz4agzzmwifuq01g1lmq8giw.min.js
```

Only `*.js` and `*.css` files are added to file `wglob` in relation to `wfind`.

Am I missing something?

**Comment by jpillora** [comment]
The ! goes at the front of the string

**Comment by jrbenito** [comment]
Hi @jpillora ,

Actually `!**/*.(css|js)` did not work, it returned nothing on my directory (full of `.html` files).

However, the solution pointed in [stackoverflow](http://stackoverflow.com/a/38679870/2726840) worked:

`**/*.!(*(*.)js|*(*.)css)`

While it is more complicated it worked flawlessly.

Thanks.
