### ISSUE TITLE
Exclude given folder no matter how deep it is?

### ISSUE THREAD

**Issue by maxime1992** [jpillora/node-glob-all#18]
Hi,

Wondering if I can exclude every `node_modules`, no matter how deep they are without using a filter function?

I thought that passing the following array of files would work, but it doesn't:
`['**/*.ts', '!node_modules']`

Thanks

**Comment by stamminator** [comment]
Your `!node_modules` pattern is only excluding that single path at the root level without considering nesting or even files inside of it. Use `!**/node_modules/**/*` to exclude not only every node_modules folder, but also everything inside them.
