### ISSUE TITLE
high severity vulnerability [Prototype Pollution] in  y18n@4.0.0

### ISSUE THREAD

**Issue by reeteshsingh** [jpillora/node-glob-all#22]
Vulnerable Package path:

glob-all@3.2.1 › yargs@15.4.1 › y18n@4.0.0

Fixed in: v5.0.5

**Comment by bwlin0331** [comment]
Bumping this, the latest version of yargs 16.2.0 should include y18n@5.0.5 if this could be addressed

**Comment by ConnorJWilliams** [comment]
Bumping this too. Any sign of this security vulnerability being patched?

**Comment by jpillora** [comment]
If someone could raise a PR resolving https://github.com/jpillora/node-glob-all/issues/25 then dependabot PRs should become mergable

**Comment by jpillora** [comment]
Published 3.3.0 thanks @hjoliveira
