### ISSUE TITLE
Glob-all destroys array of patterns

### ISSUE THREAD

**Issue by velocityzen** [jpillora/node-glob-all#5]
```js
let patterns = [
	"file",
	"anotherfile"
];

glob(patterns, 
	function(err, files) {
		err && console.log(err);
	})
	.on("match", function(f) {
		console.log(f);
	})
	.on("end", function() {
		//array is empty here
		console.log(patterns);
	})
```

**Comment by jpillora** [comment]
Ah true, this is a bug

**Comment by tepez** [comment]
I just encountered that myself.
Any plans on fixing that (or adding a warning)?

**Comment by jpillora** [comment]
Don't have the time currently though will accept a PR

**Comment by PAEz** [comment]
Really?
In about one year you couldnt find the time to change line 59 from...
this.patterns = patterns;
to
this.patterns = patterns.slice();

And yeah sure I could PR, but guess what?.....I dont have the time ;P

**Comment by CREEATION** [comment]
> And yeah sure I could PR, but guess what?.....I dont have the time ;P

Wouldn't matter I guess, two open pull requests and nothing is happening.

**Comment by jpillora** [comment]
@PAEz I know, it's outrageous, you should demand a refund
