### ISSUE TITLE
A command line interface

### ISSUE THREAD

**Issue by radek-holy** [jpillora/node-glob-all#6]
It would be nice if I could call `glob-all` from my NPM/build scripts as a portable replacement for the `find` command. I mean something like `glob-all --null < my-manifest.txt | xargs --null my-command`.

**Comment by radek-holy** [comment]
OK, I don't need this any more ([find-glob](https://www.npmjs.com/package/find-glob) is good enough). But maybe someone else does...

**Comment by jpillora** [comment]
Implemented in https://github.com/jpillora/node-glob-all/commit/f983e1a4c7610700d2c63ae7aa2628d538936f4a
